const REQUEST_CAMPAIGNS = 'REQUEST_CAMPAIGNS';
const RECEIVE_CAMPAIGNS = 'RECEIVE_CAMPAIGNS';

const REQUEST_ONE_CAMPAIGN = 'REQUEST_ONE_CAMPAIGN';
const RECEIVE_ONE_CAMPAIGN = 'RECEIVE_ONE_CAMPAIGN';

const CHANGE_PAGE_NUMBER = 'CHANGE_PAGE_NUMBER';

export default {
  REQUEST_CAMPAIGNS,
  RECEIVE_CAMPAIGNS,
  REQUEST_ONE_CAMPAIGN,
  RECEIVE_ONE_CAMPAIGN,
  CHANGE_PAGE_NUMBER,
}
