const REQUEST_ADSETS = 'REQUEST_ADSETS';
const RECEIVE_ADSETS = 'RECEIVE_ADSETS';

const REQUEST_ONE_ADSET = 'REQUEST_ONE_ADSET';
const RECEIVE_ONE_ADSET = 'RECEIVE_ONE_ADSET';

export default {
  REQUEST_ADSETS,
  RECEIVE_ADSETS,
  REQUEST_ONE_ADSET,
  RECEIVE_ONE_ADSET,
}