const REQUEST_CONSTRUCTOR_CAMPAIGN = 'REQUEST_CONSTRUCTOR_CAMPAIGN';
const RECEIVE_CONSTRUCTOR_CAMPAIGN = 'RECEIVE_CONSTRUCTOR_CAMPAIGN';

const REQUEST_ALL_CAMPAIGNS_METADATA = 'REQUEST_ALL_CAMPAIGNS_METADATA';
const RECEIVE_ALL_CAMPAIGNS_METADATA = 'RECEIVE_ALL_CAMPAIGNS_METADATA';

export default {
  REQUEST_CONSTRUCTOR_CAMPAIGN,
  RECEIVE_CONSTRUCTOR_CAMPAIGN,
  REQUEST_ALL_CAMPAIGNS_METADATA,
  RECEIVE_ALL_CAMPAIGNS_METADATA
}
